### ISSUE TITLE
support for rubocop?

### ISSUE THREAD

**Issue by twnaing** [mihyaeru21/nvim-lspconfig-bundler#3]
Do you have plan to add rubocop support?

rubocop `--lsp` is available in 1.53+

Current nvim-lspconfig default implementation (using `on_new_config`) is not working for my case. However, adding 

```lua
	rubocop = {
		gem = "rubocop",
	},
```

works for me.

**Comment by mihyaeru21** [comment]
@twnaing 
I have added the suggested configuration to work with RuboCop as well!

**Comment by mihyaeru21** [comment]
I plan to port the logic of nvim-lspconfig-bundler to nvim-lspconfig later. After that, this plug-in is no longer needed.
